# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjenkins < Formula
  desc "Lazygit-style TUI for the jk Jenkins CLI"
  homepage "https://github.com/rgsoda/lazyjenkins"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgsoda/lazyjenkins/releases/download/v0.8.0/lazyjenkins_darwin_amd64.tar.gz"
      sha256 "d2fe3391e83ba3644c03317fbeb91d981566b8eca1008d2b16e58bacdc8c9a17"

      define_method(:install) do
        bin.install "lazyjenkins"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgsoda/lazyjenkins/releases/download/v0.8.0/lazyjenkins_darwin_arm64.tar.gz"
      sha256 "02e2bf55e8b8f3caf20d7e4bba007645b068140392405ee79f7e040b937eca82"

      define_method(:install) do
        bin.install "lazyjenkins"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgsoda/lazyjenkins/releases/download/v0.8.0/lazyjenkins_linux_amd64.tar.gz"
      sha256 "424c6d207b1ab4473d2bb0323da7b7c36d7ec4d6e23fae6b02c732d9e1b9b261"
      define_method(:install) do
        bin.install "lazyjenkins"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgsoda/lazyjenkins/releases/download/v0.8.0/lazyjenkins_linux_arm64.tar.gz"
      sha256 "41b5367bf990898a16abb8483320c961ade3ea57e9c00ef8a0a930e204624d80"
      define_method(:install) do
        bin.install "lazyjenkins"
      end
    end
  end

  test do
    assert_path_exists bin/"lazyjenkins"
  end
end
