# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjenkins < Formula
  desc "Lazygit-style TUI for the jk Jenkins CLI"
  homepage "https://github.com/rgsoda/lazyjenkins"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rgsoda/lazyjenkins/releases/download/v0.6.0/lazyjenkins_darwin_amd64.tar.gz"
      sha256 "6754f6e2ec0dede87fba574a7facdc47c921ff7c20ce61d62654e5dc181d3b43"

      define_method(:install) do
        bin.install "lazyjenkins"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rgsoda/lazyjenkins/releases/download/v0.6.0/lazyjenkins_darwin_arm64.tar.gz"
      sha256 "8fc18b1b1032427bc34326766c219f66d0afb8d85a37368b2d1c16154c229fbf"

      define_method(:install) do
        bin.install "lazyjenkins"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgsoda/lazyjenkins/releases/download/v0.6.0/lazyjenkins_linux_amd64.tar.gz"
      sha256 "d2e70282be11d66ac352715470353efd21397a13ad17030b75b8b049678c399f"
      define_method(:install) do
        bin.install "lazyjenkins"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rgsoda/lazyjenkins/releases/download/v0.6.0/lazyjenkins_linux_arm64.tar.gz"
      sha256 "5825b904d58f37fd03cda4135190ea617b336d7be1ea3cf9c29cb298d991d921"
      define_method(:install) do
        bin.install "lazyjenkins"
      end
    end
  end

  test do
    assert_path_exists bin/"lazyjenkins"
  end
end
